// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsWCVQR3-AUmfudpidwqP0dkmGqzgB27Y',
    appId: '1:883613682630:web:cc9a462b1caafaaaad00c7',
    messagingSenderId: '883613682630',
    projectId: 'vidshare-71e04',
    authDomain: 'vidshare-71e04.firebaseapp.com',
    storageBucket: 'vidshare-71e04.appspot.com',
    measurementId: 'G-ZQR7GKTHJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLjbqE8WjbEBS4I76SGRRw1NrBTtRzuwE',
    appId: '1:883613682630:android:f0bffe192ca8c9eaad00c7',
    messagingSenderId: '883613682630',
    projectId: 'vidshare-71e04',
    storageBucket: 'vidshare-71e04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrlx63QjuEc9sudPBQblfxLWUVecG4WBY',
    appId: '1:883613682630:ios:ce83b5ab28c9df38ad00c7',
    messagingSenderId: '883613682630',
    projectId: 'vidshare-71e04',
    storageBucket: 'vidshare-71e04.appspot.com',
    iosBundleId: 'com.example.vidShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrlx63QjuEc9sudPBQblfxLWUVecG4WBY',
    appId: '1:883613682630:ios:cacee2ea2a185970ad00c7',
    messagingSenderId: '883613682630',
    projectId: 'vidshare-71e04',
    storageBucket: 'vidshare-71e04.appspot.com',
    iosBundleId: 'com.example.vidShare.RunnerTests',
  );
}
